# Docker Compose Development Overrides
# This file is automatically loaded by docker-compose for development

version: '3.8'

services:
  backend:
    build:
      target: build  # Use build stage for development
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
    volumes:
      # Enable hot reloading in development
      - ./backend/src:/app/src:ro
      - ./backend/package.json:/app/package.json:ro
      - ./backend/tsconfig.json:/app/tsconfig.json:ro
      - ./backend/nodemon.json:/app/nodemon.json:ro
    command: ["npm", "run", "dev"]  # Use development command with hot reload
    
  postgres:
    ports:
      - "5432:5432"  # Expose postgres port for development tools
    environment:
      - POSTGRES_PASSWORD=dev_password  # Simpler password for development
    
  redis:
    ports:
      - "6379:6379"  # Expose redis port for development tools