version: "3.8"

services:
  workspace:
    image: mcr.microsoft.com/devcontainers/typescript-node
    init: true
    command: sleep infinity
    environment:
      DOCKER_ENV: "true"
      POSTGRES_HOST: postgres
      REDIS_HOST: redis
    volumes:
      - ..:/workspaces/project-nexus:cached
      - workspace-node-home:/home/node
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: nexus
      POSTGRES_PASSWORD: nexus_secure_2024
      POSTGRES_DB: nexus_db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nexus"]
      interval: 10s
      timeout: 5s
      retries: 5
    mem_limit: 512m

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: ["redis-server", "--save", "", "--appendonly", "no", "--maxmemory", "128mb", "--maxmemory-policy", "allkeys-lru"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    mem_limit: 256m

  adminer:
    image: adminer:4-standalone
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DEFAULT_USER: nexus
      ADMINER_DEFAULT_PASSWORD: nexus_secure_2024
      ADMINER_DEFAULT_DB: nexus_db
    ports:
      - "8080:8080"
    volumes:
      - ./adminer-auto.php:/var/www/html/index.php:ro
    mem_limit: 256m

volumes:
  workspace-node-home:
  postgres-data:
  redis-data:
